"""added index for some columns

Revision ID: c96f24801f9e
Revises: ac91c3d0571d
Create Date: 2025-10-07 10:03:22.543921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96f24801f9e'
down_revision: Union[str, Sequence[str], None] = 'ac91c3d0571d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('authors_name_key'), 'authors', type_='unique')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_unique_constraint(op.f('authors_name_key'), 'authors', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
